//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskGame.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameRoom> GameRooms { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<RiskOption> RiskOptions { get; set; }
        public virtual DbSet<UserGameBattle> UserGameBattles { get; set; }
        public virtual DbSet<UserGameRoom> UserGameRooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserGameBattleLog> UserGameBattleLogs { get; set; }
        public virtual DbSet<UserGameRisk> UserGameRisks { get; set; }
        public virtual DbSet<GameBattle> GameBattles { get; set; }
    }
}
