//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskGame.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskOption
    {
        public int RiskOptionId { get; set; }
        public Nullable<int> RiskId { get; set; }
        public Nullable<int> RiskLevel { get; set; }
        public Nullable<int> ActionEffectType { get; set; }
        public Nullable<int> ActionEffectValue { get; set; }
        public Nullable<int> RiskImpact { get; set; }
        public Nullable<int> RiskPorture { get; set; }
    
        public virtual Risk Risk { get; set; }
    }
}
