//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskGame.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskNews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskNews()
        {
            this.GameBattles = new HashSet<GameBattle>();
        }
    
        public int RiskNewsId { get; set; }
        public int RiskId { get; set; }
        public string RiskNewsDetail { get; set; }
        public Nullable<int> RiskNewsProbability { get; set; }
        public Nullable<int> RiskNewsImpact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameBattle> GameBattles { get; set; }
        public virtual Risk Risk { get; set; }
    }
}
