//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskGame.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskOption()
        {
            this.UserGameRisks = new HashSet<UserGameRisk>();
            this.GameBattles = new HashSet<GameBattle>();
        }
    
        public int RiskOptionId { get; set; }
        public Nullable<int> RiskId { get; set; }
        public Nullable<int> RiskLevel { get; set; }
        public Nullable<int> ActionEffectType { get; set; }
        public Nullable<int> ActionEffectValue { get; set; }
        public Nullable<int> RiskImpact { get; set; }
        public Nullable<int> RiskPorture { get; set; }
    
        public virtual Risk Risk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGameRisk> UserGameRisks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameBattle> GameBattles { get; set; }
    }
}
